# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-12 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.DecimalField(decimal_places=0, max_digits=3)),
                ('name', models.CharField(max_length=200)),
                ('team', models.CharField(max_length=200)),
                ('average', models.CharField(max_length=200)),
                ('stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Stat')),
            ],
        ),
    ]
