# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_number', models.CharField(max_length=3)),
                ('person_name', models.CharField(max_length=200)),
                ('person_position', models.CharField(max_length=50)),
                ('person_image', models.FileField(upload_to='')),
                ('person_age', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('team_logo', models.FileField(upload_to='')),
                ('city', models.CharField(max_length=200)),
                ('city_image', models.FileField(upload_to='')),
                ('history', models.CharField(max_length=2000)),
                ('arena', models.CharField(max_length=200)),
                ('arena_image', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.Team'),
        ),
    ]
