# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-29 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=200)),
                ('player_face', models.FileField(upload_to='')),
                ('player_position', models.CharField(max_length=200)),
                ('player_nationality', models.CharField(max_length=200)),
                ('date_of_birth', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gp', models.CharField(max_length=10)),
                ('mpg', models.CharField(max_length=10)),
                ('ppg', models.CharField(max_length=10)),
                ('apg', models.CharField(max_length=10)),
                ('rpg', models.CharField(max_length=10)),
                ('spg', models.CharField(max_length=10)),
                ('bpg', models.CharField(max_length=10)),
                ('field_goal_percentage', models.CharField(max_length=10)),
                ('three_point_percentage', models.CharField(max_length=10)),
                ('index', models.CharField(max_length=10)),
                ('full_stats', models.FilePathField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Player')),
            ],
        ),
    ]
