# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-29 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_auto_20171229_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stat',
            name='full_stats',
        ),
    ]
