# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-29 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_remove_stat_full_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_height',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
