# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-26 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_player_player_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='ft_percentage',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
