# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-26 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_stat_ft_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stat',
            name='player',
        ),
        migrations.AddField(
            model_name='player',
            name='player_stats',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Stat',
        ),
    ]
