# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-10 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_auto_20180126_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='assists',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='stat',
            name='blocks',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='stat',
            name='index',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='stat',
            name='rebounds',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='stat',
            name='steals',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='stat',
            name='turnovers',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
    ]
