# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-10 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_auto_20180210_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='points',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
    ]
